# config.toml
# Default configuration for AI Cost Estimator
# Values here can be overridden by environment variables in .env

[app]
name = "cost-estimator"
version = "1.0.0"
debug = true

[estimator]
logic_variant = "cost-estimator-core"
currency = "USD"
s3_bucket = "ai-cost-estimator-data"
