services:
  app:
    build: .
    container_name: ai-cost-estimator
    ports:
      - "8000:8000"
    env_file: ".env"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s